src/Player.js
src/Turn.js
src/data/data.js
test/Player-test.js
test/Turn-test.js

Set up Turn and Player classes @SamanthaLFreeman @Jessiewithani

Set up Turn and Player classes

---

src/Turn.js
test/Turn-test.js

Set up Turn class methods and pseudocoded next steps @SamanthaLFreeman @Jessiewithani

Set up Turn class methods and pseudocoded next steps

---

src/index.js
test/game-test.js
test/round-test.js
test/sample-test.js

finished creating the round test

Finish round test

---

src/round.js
test/Clue-test.js
test/round-test.js

Hello Yana and Samantha,
I've created the method to return the daily double according to the round. Please check it out, and give me your feedback.
Thank you,
Jessie

Create daily double method

---

src/DOMupdates.js
test/Clue-test.js
test/Player-test.js
test/Turn-test.js
test/game-test.js
test/round-test.js

Hey team,
This PR includes a new DOMupdates.js file, which will house all jQuery updates to the DOM. In addition, I've added the chai spies import to all of our test files. Thank you!

DOM updates initial file

---

src/round.js
test/round-test.js

I created a method so far but still have more to add. This is what I have so far.

Make round methods and add tests

---

src/Clue.js
test/Clue-test.js

Hey group,
This PR updates the Clue class to accept the data. Then there is methods to filter out 4 categories and then find cards that match these 4 categories. The final solution will be an array of all 16 questions in descending order. Thank you!

Data filter clue

---

src/index.html
src/index.js

Hey group,
I've created the initial HTML file including all of the features we need at this time. Please note I've added classes and ids to all of the tags. My intention is for classes to be used for styling and ids can be used for JavaScript.

Add initial HTML file

---

src/DOMupdates.js
src/Player.js
src/Turn.js
src/data/data.js
test/Clue-test.js
test/Player-test.js
test/Turn-test.js

Hi team @SamanthaLFreeman @Jessiewithani @robbiejaeger 
I got these methods up and running: evaluateGuess, giveFeedback and updateScore methods in Turn class, please check them out. Tests are also working for them. 
One thing i wanted to check with you is if our dailyDouble working now?

Set up updateScore method 

---

src/Clue.js
src/Clues.js
src/DOMupdates.js
src/css/base.scss
src/index.html
src/index.js
test/Clue-test.js
test/Clues-test.js
test/round-test.js

Hey group,
This PR adds categories and clues based on the current test data. Please note, we still need to incorporate fetch API and I need to clean up because the questions and categories are not matching up yet.

Display categories

---

src/DOMupdates.js
src/index.js

displayed the player name on the dom

Display player names on DOM

---

src/DOMupdates.js
src/index.js

i got the player score to show up on the DOM as well.

Display player score

---

src/Turn.js
src/game.js
src/index.html
src/index.js

Hey @yaleksandrova,
I fixed the turn class instance, because it was currently passing through all game data that was fetched. Instead I changed it so that the clues class is passed through, which is what is actually filtering the data.

Pass clues class through turn instance

---

src/DOMupdates.js
src/index.html
src/index.js

hey group,
I've got questions to finally appear upon clicking them

Make questions display

---

src/DOMupdates.js
src/css/base.scss
src/index.html
src/index.js

Hey Group,
I've cleaned up some of the CSS to display the page in a grid format.

CSS structure

---

src/index.html

Add dollar sign

---

src/DOMupdates.js
src/index.js
test/Clues-test.js

Hey group,
The Clues tests broke after I restructured the class, so I have fixed them to correctly check that the correct length of the array is returned.

Fix clues tests after the class change, which broke two of the tests

---

src/Clues.js
src/DOMupdates.js
src/Turn.js
src/game.js
src/index.js
src/round.js

Add wager method 

---

src/DOMupdates.js
src/Turn.js
src/index.js

Fix evaluate guess

---

src/DOMupdates.js
src/Turn.js
src/index.html
src/index.js

hey @robbiejaeger, this is our progress so far. Forgot to add the co author  tag on the commit. 
co-authored with @yaleksandrova and @SamanthaLFreeman

Display incorrect/correct

---

src/DOMupdates.js
src/Turn.js
src/index.js
src/round.js

co- authored-by: Sam Freeman <freemasl.sf@gmail.com>
co-authored-by: Jessie Le-Ho <lehoj@oregonstate.edu>

Update change player

---

src/DOMupdates.js
src/Player.js
src/Turn.js
src/game.js
src/index.html
src/index.js
src/round.js

Hey everyone,
This branch show's the current player on the display, increments/decrements score on the DOM, hides the question after the player submits their answer and keeps track when the round has ended.
@robbiejaeger

Show current player

---

src/DOMupdates.js

Hey Group,
I've fixed the cards, so that they disable once the question has been removed from the DOM. In addition, cleaned up the repeated code in the method.

Disable cards after the card has been cleared from the DOM
